name: feature_based_mvvm_architecture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter



  google_fonts: ^6.1.0
  carousel_slider: ^5.0.0
  easy_stepper: ^0.8.5+1
  shimmer: ^3.0.0
  dotlottie_loader: ^0.0.5
  lottie: ^3.3.1
  animated_list_plus: ^0.5.2
  logger: ^2.5.0
  image_picker: ^1.1.2
  pinput: ^5.0.1
  # fluttertoast: ^8.1.1
  # webview_flutter: ^4.2.2
  # flutter_native_splash: ^2.3.1
  # badges: ^3.1.1
  # carousel_slider: ^4.2.1
  flutter_screenutil: ^5.5.3+2
  provider: ^6.0.3
  dio: ^5.1.2
  # url_launcher: ^6.1.5
  flutter_svg: ^2.0.7
  # getwidget: ^4.0.0
  # flutter_switch: ^0.3.2
  # file_picker: ^6.1.1
  # google_maps_flutter: ^2.1.8
  rxdart: ^0.28.0
  get_storage: ^2.0.3
  get_it: ^8.0.3
  # http: ^1.1.0
  intl: ^0.19.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4 
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.3.3
  path_provider: ^2.1.5
  # flutter_app_badger: ^1.4.0
  # geolocator: ^10.0.0
  # geocoding: ^2.1.0
  # liquid_pull_to_refresh: ^3.0.1
  internet_connection_checker: ^3.0.1
  # flutter_rating_bar: ^4.0.1
  # package_info_plus: ^5.0.1
  # google_sign_in: ^6.1.6
  # lottie: ^3.0.0
  # dotlottie_loader: ^0.0.3
  cupertino_icons: ^1.0.0
  # flutter_polyline_points: ^2.0.0
  # location: ^5.0.3
  fluttertoast: ^8.2.12
  cached_network_image: ^3.3.1
  go_router: ^14.8.1
  flutter_rating: ^2.0.2
  # either_dart: ^1.0.0'
  device_preview:
  dropdown_button2: ^2.3.9
  rating_summary: ^1.0.4
  flutter_rating_stars: ^1.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  animation_list: ^3.1.0
  flutter_html: ^3.0.0

dev_dependencies:
  dependency_validator: ^4.0.0
  build_runner:
  hive_generator: ^2.0.1
  flutter_gen_runner:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: false

    rive: false
    lottie: false
    
  colors:
    inputs:
      - assets/color/colors.xml

    outputs:
      class_name: AppColors



flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
